apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suitemedia.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "suitemedia.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
