apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    name: {{ .Values.namespace | default .Release.Namespace }}
    {{- include "suitemedia.labels" . | nindent 4 }}
