{{- if .Values.verticalPodAutoscaling.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "suitemedia.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "suitemedia.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "suitemedia.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaling.updateMode }}
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Chart.Name }}
      minAllowed:
        {{- toYaml .Values.verticalPodAutoscaling.minAllowed | nindent 8 }}
      maxAllowed:
        {{- toYaml .Values.verticalPodAutoscaling.maxAllowed | nindent 8 }}
{{- end }}
